# Generated by Django 3.1.2 on 2020-10-13 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(default=0)),
                ('status', models.CharField(choices=[(1, 'criado'), (2, 'aguardando_docs'), (3, 'aprovado'), (4, 'analisado')], default=(1, 'criado'), max_length=50)),
                ('statusAprovacao', models.CharField(choices=[(1, 'analisando'), (2, 'aprovado'), (3, 'rejeitado')], default=(1, 'analisando'), max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('cpf', models.CharField(max_length=30)),
                ('renda', models.FloatField()),
                ('rua', models.CharField(max_length=60)),
                ('numero', models.IntegerField()),
                ('bairro', models.CharField(max_length=30)),
                ('cidade', models.CharField(max_length=30)),
                ('estado', models.CharField(max_length=2)),
                ('estadoCivil', models.CharField(max_length=30)),
                ('dataNascimento', models.DateField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[(1, 'CPF'), (2, 'CNH')], default=(1, 'CPF'), max_length=50)),
                ('urlimagens', models.CharField(max_length=1000)),
                ('urlcomprovanteRenda', models.CharField(max_length=1000)),
                ('contratoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratosAPI.contrato')),
            ],
        ),
        migrations.AddField(
            model_name='contrato',
            name='usuarioId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratosAPI.user'),
        ),
    ]
