# Generated by Django 3.1.2 on 2020-10-13 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratosAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='urlcomprovanteRenda',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='documento',
            name='urlimagens',
            field=models.CharField(max_length=1000),
        ),
    ]
